version: '3.4'

networks:
    secrets-world:
    secrets-internal:

services:

    #secrets
    vault:
        image: vault:1.7.2
        container_name: vault
        networks: 
            - secrets-internal
        environment: 
            - VAULT_API_ADDR=http://0.0.0.0:8202
            - VAULT_ADDR=http://0.0.0.0:8200
            - VAULT_DEV_ROOT_TOKEN_ID=secret
            - VAULT_TOKEN=secret
        volumes:
            - ./vault/config:/vault/config
            - ./vault/policies:/vault/policies
            - ./_data/vault:/vault/data
            - ./vault/file:/vault/file
            - ./vault/logs:/vault/logs
        cap_add:
            - IPC_LOCK
        ports:
            - "8200:8200"

    #PHP / FPM / FastCgi
    php:
        container_name: php
        volumes:
            - ./api:/var/www/api
            - ./docker/php-fpm/sockets:/run/php
            - ./docker/php-fpm/listen.conf:/etc/php/7.4/fpm/pool.d/www.conf
            - ./docker/api/uploads.ini:/etc/php/7.4/fpm/conf.d/90-uploads.ini
            - ./docker/api/xdebug.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini
        build:
            context: .
            dockerfile: Dockerfile-php
        ports:
            - "9123:9000"
        networks:
            - secrets-internal
        working_dir: /var/www
        command:
            /usr/sbin/php-fpm7.4 -F -R -O

    # API web server
    api-web:
        image: nginx:1.19-alpine
        container_name: api-web
        restart: "no"
        ports:
            - "8321:80"
        volumes:
            - ./api:/var/www/api
            - ./docker/api/nginx.conf:/etc/nginx/conf.d/default.conf   
        networks:
            - secrets-world
            - secrets-internal

    #Frontend (development)
    frontend:
        image: node:12.18-alpine
        container_name: frontend
        restart: "no"
        ports:
            - "8123:80"
        volumes:
            - ./docker/front-end/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
            - ./front-end:/var/dev 
            - ./docker/front-end/locks:/root/locks
        networks:
            - secrets-world
        working_dir: /var/dev
        

    #Database
    db-operator-x:
        image: mysql:8.0
        container_name: db-operator-x
        restart: "no"
        tty: true
        ports:
            - "33061:3306"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_DATABASE: operator-x
            MYSQL_USER: vault
            MYSQL_PASSWORD: vault
            MYSQL_ROOT_PASSWORD: vault
        networks:
            - secrets-internal
        volumes:
            - ./_data/db-operator-x:/var/lib/mysql
            - ./docker/provision/db:/docker-entrypoint-initdb.d

        
    #Database
    db-operator-y:
        image: mysql:8.0
        container_name: db-operator-y
        restart: "no"
        tty: true
        ports:
            - "33062:3306"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_DATABASE: operator-y
            MYSQL_USER: vault
            MYSQL_PASSWORD: vault
            MYSQL_ROOT_PASSWORD: vault
        networks:
            - secrets-internal
        volumes:
            - ./_data/db-operator-y:/var/lib/mysql
            - ./docker/provision/db:/docker-entrypoint-initdb.d

        
    #Database
    db-operator-z:
        image: mysql:8.0
        container_name: db-operator-z
        restart: "no"
        tty: true
        ports:
            - "33063:3306"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_DATABASE: operator-z
            MYSQL_USER: vault
            MYSQL_PASSWORD: vault
            MYSQL_ROOT_PASSWORD: vault
        networks:
            - secrets-internal
        volumes:
            - ./_data/db-operator-z:/var/lib/mysql
            - ./docker/provision/db:/docker-entrypoint-initdb.d